name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean build
      run: dotnet clean backend/microservices/user-service/user-service.csproj

    - name: Restore dependencies
      run: dotnet restore backend/microservices/user-service/user-service.csproj

    - name: Build
      run: dotnet build backend/microservices/user-service/user-service.csproj --no-restore

    - name: Test
      run: dotnet test backend/microservices/user-service/user-service.csproj --no-build --verbosity normal
